[package]
name = "rumpy"
version = "0.1.0"
edition = "2021"

[lib]
name = "rumpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
bitflags = "2.6"
